Add JSON lexer
MakeNowJust/noir pull request #33
Opened 2018-12-20 09:58 UTC by fabon-f

2018-12-20 10:29 UTC, makenowjust commented on src/noir/lexers/json.cr
> +    rule /true|false|null/, Keyword::Constant
I prefer to wrap `\b` around keywords for correctness.

2018-12-20 10:32 UTC, makenowjust commented
It works well in respect of JSON following RFC 8259 exactly. I think, however, syntax highlighters should work permissively. For example `tsconfig.json` accept JS like comments. What do you think?

2018-12-21 01:34 UTC, fabon-f commented on src/noir/lexers/json.cr
> +    rule /true|false|null/, Keyword::Constant
I fixed it.

2018-12-21 02:16 UTC, makenowjust requested changes

2018-12-21 02:16 UTC, MakeNowJust commented on src/noir/lexers/json.cr
> +    rule /(true|false|null)\b/, Keyword::Constant
Add `\b` to both sides. For instance it matches `"true"` on `"xtrue"`.

2018-12-21 05:07 UTC, makenowjust approved these changes

2018-12-21 05:07 UTC, MakeNowJust commented
Sorry, closing this PR is my mistaken.

I surveyed JSON language definition of some syntax highlighters, and there is no highlighter to accept comment. (However VSCode has language definition for JSON with comments.) So, it is ready to merge now.

Thank you @fabon-f for contribution.

2018-12-21 05:07 UTC, merged